services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\SoccerCalendarBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Endroid\SoccerCalendar\Factory\CalendarFactory:
        public: true

    Endroid\SoccerData\Vi\Client: ~
    Endroid\SoccerData\Vi\Loader\CompetitionLoader: ~
    Endroid\SoccerData\Vi\Loader\TeamLoader: ~
    Endroid\SoccerData\Vi\Loader\GameLoader: ~
    Endroid\SoccerData\Loader\CompetitionLoaderInterface: '@Endroid\SoccerData\Vi\Loader\CompetitionLoader'
    Endroid\SoccerData\Loader\TeamLoaderInterface: '@Endroid\SoccerData\Vi\Loader\TeamLoader'
    Endroid\SoccerData\Loader\GameLoaderInterface: '@Endroid\SoccerData\Vi\Loader\GameLoader'

    Endroid\Calendar\Writer\IcalWriter: ~
